ferreteria/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from app.views import *
from app.Views.productoView import *
from app.Views.precioView import *
from app.Views.presentacionView import *
from app.Views.aperturacajaView import *
from app.Views.cierrecajaView import *
from app.Views.operacionView import *
from app.Views.pedidoView import *
from app.Views.usuarioView import *
from app.Views.clienteView import *
from app.Views.rutaView import *
from app.Views.visitaView import *
from app.Views.errorView import *
from app.Views.ventaView import *
from app.Views.loteView import *
###########################################################
#   Usuario: Erick Sulca, Ulises Bejar
#   Fecha: 05/06/18
#   Última modificación:
#   Descripción: url registrarError
###########################################################

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home),
    url(r'^login/$', Login),
    url(r'^logout/$', Logout),
    url(r'^home/$', Home),
    url(r'^Home/$', Home),
    url(r'^prueba/$', Prueba),

    ################## Caja #######################
    url(r'^Caja/apertura/$', registrarAperturacaja),
    url(r'^Caja/cierre/$', registrarCierrecaja),
    url(r'^Caja/movimiento/$', registrarOperacion),

    ################## Venta #######################
    url(r'^Venta/nuevo/$', registrarPedido),

    ################## Producto #######################
    url(r'^Producto/listar/$', ListarProductos),
    url(r'^Producto/nuevo/$', registrarProducto),
    url(r'^Producto/detalle/(?P<producto_id>\d+)/$', detalleProducto),
    url(r'^Producto/editar/(?P<producto_id>\d+)/$', editarProducto),

    ################## Catalogo #######################
    url(r'^Presentacion/Listar/(?P<producto_id>\d+)/$', presentacion_detalle),
    url(r'^Presentacion/registrar/$', registrarPresentacionProducto),
    url(r'^Presentacion/eliminar/(?P<presentacion_id>\d+)/(?P<producto_id>\d+)/$', eliminarPresentacionProducto),
    url(r'^Presentacion/getPresentaciones/$', getPresentaciones),
    
    url(r'^Precios/getPrecios/$', getPrecios),
    #url(r'^pruebaExcel/$', IngresarPrecios),

    ################## Cliente #######################
    url(r'^Cliente/nuevo/$', nuevoCliente),
    url(r'^Cliente/detalle/(?P<cliente_id>\d+)/$', detalleCliente),
    url(r'^Cliente/editar/(?P<cliente_id>\d+)/$', editarCliente),
    url(r'^Cliente/listar/$', listarCliente),
    url(r'^Cliente/buscar/$', IngresarPrecios),
    url(r'^Cliente/actualizar/$', IngresarPrecios),
    
    ################## Pedidos #######################

    url(r'^Pedido/nuevo/$', registrarPedido),
    url(r'^Pedido/listar/$', ListarPedidos),
    url(r'^Pedido/resumen/$', ResumenPedidos),
    url(r'^Pedido/detalle/(?P<pedido_id>\d+)/$', DetallePedido),
    url(r'^Pedido/editar/(?P<pedido_id>\d+)/$', editarPedido),
    url(r'^Pedido/eliminar/(?P<pedido_id>\d+)/$', eliminarPedido),
    url(r'^Pedido/actualizar/$', IngresarPrecios),
    url(r'^Pedido/reporte/$', IngresarPrecios),
    url(r'^Pedido/buscar/$', IngresarPrecios),
    url(r'^Pedido/imprimir/$', IngresarPrecios),
    
    
    ################## APP Movil #######################
    
    url(r'^usuario/validar/$', validarUsuario),
    url(r'^usuario/ruta/$', rutaUsuario),

    url(r'^usuario/visita/cancelar/$', cancelarVisita),
    url(r'^usuario/visita/reiniciar/$', reiniciarVisita),

    url(r'^cliente/buscar/$', buscarCliente),
    url(r'^cliente/detalle/$', detalleClienteWS),

    url(r'^pedido/insertar/$', InstarPedido),
    url(r'^pedido/listar/$', ListarPedido),
    url(r'^pedido/detalle/$', DetallePedidoMovil),
    url(r'^pedido/editar/$', DetallePedidoMovil),

    url(r'^pago/nuevo/$', IngresarPrecios),


    url(r'^producto/buscar/$', BuscarProducto),
    url(r'^producto/presentacion/listar/$', ListarPresentacionesProducto),
    url(r'^producto/presentacion/cantidad/$', CantidadPresentacionesProducto),
    
    url(r'^error/registrar/$', registrarError),


#######################Ventas##############################

    url(r'^venta/nuevo/$', nuevoVenta),
    url(r'^venta/listar/$', ListarVentas),
    #url(r'^Producto/detalle/(?P<producto_id>\d+)/$', detalleProducto),
    #url(r'^Producto/editar/(?P<producto_id>\d+)/$', editarProducto),

    url(r'^Lote/nuevo/$', nuevoLote),
    #####################################################

#######################Rutas##############################

    #url(r'^Ruta/nuevo/$', nuevoVenta),
    #url(r'^Ruta/listar/$', ListarVenta),

#######################Información y Reportes##############################
    
    #url(r'^Reporte/almacen/$', reporteAlmacen),
    #url(r'^Reporte/caja/$', reporteCaja),
    #url(r'^Reporte/ventas/$', reporteVentas),

]

app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals
 
from django.db import models

###########################################################
#   Usuario: Erick Sulca, Ulises Bejar
#   Fecha: 04/06/18
#   Última modificación:
#   Descripción: crear modelo Error, etc
###########################################################

class Almacen(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

class Caja(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

class Aperturacaja(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=False)
    monto = models.FloatField()
    activo = models.BooleanField(blank=True,default=True)
    estado = models.BooleanField(blank=True,default=True)
    caja = models.ForeignKey(Caja, on_delete=models.CASCADE)

class Categoria(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

class Cierrecaja(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    monto = models.FloatField()
    estado = models.BooleanField(blank=True,default=True)
    aperturacaja = models.ForeignKey(Aperturacaja, on_delete=models.CASCADE)  # Field name made lowercase.

class Cliente(models.Model):
    nombre = models.CharField(max_length=45)
    direccion = models.CharField(max_length=45)
    longitud = models.CharField(max_length=25, blank=True, null=True)
    latitud = models.CharField(max_length=25, blank=True, null=True)
    numerodocumento = models.CharField(max_length=11, blank=True, null=True)
    estado = models.BooleanField(blank=True,default=True)

class Cobro(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    monto = models.FloatField()
    estado = models.BooleanField(blank=True,default=True)
    venta = models.ForeignKey('Venta', on_delete=models.CASCADE)  # Field name made lowercase.
    recibo = models.ForeignKey('Recibo', blank=True, null=True, on_delete=models.CASCADE)  # Field name made lowercase.

class Detalletipooperacion(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)
    tipooperacion = models.ForeignKey('Tipooperacion', on_delete=models.CASCADE)  # Field name made lowercase.

class Lote(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    modificado = models.DateTimeField(auto_now=True, blank=True)
    estado = models.BooleanField(blank=True,default=True)
    proveedor = models.ForeignKey('Proveedor', on_delete=models.CASCADE)  # Field name made lowercase.
    recibo = models.ForeignKey('Recibo', on_delete=models.CASCADE)  # Field name made lowercase.

class Operacion(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    monto = models.FloatField()
    descripcion = models.TextField(blank=True, null=True)
    estado = models.BooleanField(blank=True,default=True)
    caja = models.ForeignKey(Caja, on_delete=models.CASCADE)  # Field name made lowercase.
    detalletipooperacion = models.ForeignKey(Detalletipooperacion, on_delete=models.CASCADE)  # Field name made lowercase.
    cobro = models.ForeignKey(Cobro, blank=True, null=True, on_delete=models.CASCADE)  # Field name made lowercase.

class Pedido(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    estado = models.BooleanField(blank=True,default=True)
    empleado = models.ForeignKey('Empleado', on_delete=models.CASCADE)  # Field name made lowercase.
    cliente = models.ForeignKey(Cliente, blank=True, null=True, on_delete=models.CASCADE)  # Field name made lowercase.

class Precio(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

class Presentacion(models.Model):
    nombre = models.CharField(max_length=45)
    codigo = models.CharField(max_length=45, blank=True, null=True)
    estado = models.BooleanField(blank=True,default=True)

class Empleado(models.Model):
    nombre = models.CharField(max_length=45)
    imei = models.CharField(max_length=45, blank=True, null=True)
    imagen = models.ImageField(blank=True, null=True)#upload_to='%Y/%m/%d',
    perfil = models.IntegerField(blank=True, null=True,default=1)
    estado = models.BooleanField(blank=True,default=True)

class Producto(models.Model):
    nombre = models.CharField(max_length=45)
    codigo = models.CharField(max_length=45, blank=True, null=True)
    cantidad = models.FloatField(default=0,blank=True, null=True)
    imagen = models.ImageField(upload_to='', blank=True, null=True)#upload_to='%Y/%m/%d',
    url = models.CharField(max_length=100, blank=True, null=True)
    valor = models.FloatField(default=1,blank=True)
    estado = models.BooleanField(blank=True,default=True)
    presentacions = models.ManyToManyField(Presentacion)

class Productopresentacions(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE) 
    presentacion = models.ForeignKey(Presentacion, on_delete=models.CASCADE)  
    valor = models.FloatField()
    unidadprincipal = models.BooleanField(default=False,blank=True)
    precios = models.ManyToManyField(Precio)
    class Meta:
        managed = False
        db_table = 'app_producto_presentacions'

class Producto_almacens(models.Model):
    cantidad = models.FloatField()
    cantidadinicial = models.FloatField()
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)  # Field name made lowercase.
    almacen = models.ForeignKey(Almacen, on_delete=models.CASCADE)  # Field name made lowercase.
    lote = models.ForeignKey(Lote, on_delete=models.CASCADE)  # Field name made lowercase.

class Producto_categorias(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)  # Field name made lowercase.
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)  # Field name made lowercase.

class Proveedor(models.Model):
    nombre = models.CharField(max_length=45)
    direccion = models.CharField(max_length=45)
    documento = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

class Recibo(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

class Tipooperacion(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

class Venta(models.Model):
    fecha   = models.DateTimeField(auto_now_add=True, blank=True)
    monto   = models.FloatField()
    nrecibo = models.CharField(max_length=45, blank=True, null=True)
    estado  = models.BooleanField(blank=True,default=True)
    pedido  = models.ForeignKey(Pedido, on_delete=models.CASCADE)  # Field name made lowercase.
    cliente = models.ForeignKey(Cliente, blank=True, null=True, on_delete=models.CASCADE)  # Field name made lowercase.
 
class Pedidoproductospresentacions(models.Model):
    valor                 = models.FloatField(blank=True, null=True)
    cantidad              = models.FloatField(blank=True,default=0)
    pedido                = models.ForeignKey(Pedido, on_delete=models.CASCADE)  # Field name made lowercase.
    productopresentacions = models.ForeignKey('Productopresentacions', on_delete=models.CASCADE)  # Field name made lowercase.
    class Meta:
        managed = False
        db_table = 'app_pedido_productos_presentacions'

class Productopresentacionsprecios(models.Model):
    precio                = models.ForeignKey(Precio, on_delete=models.CASCADE)  # Field name made lowercase.
    productopresentacions = models.ForeignKey('Productopresentacions', on_delete=models.CASCADE)  # Field name made lowercase.
    valor                 = models.FloatField(blank=True,default=0)
    class Meta:
        managed = False
        db_table = 'app_producto_presentacions_precios'


class Ruta(models.Model):
    nombre   = models.CharField(max_length=45)
    fecha    = models.DateTimeField(auto_now_add=True, blank=True)
    activo   = models.BooleanField(blank=True,default=True)
    estado   = models.BooleanField(blank=True,default=True)
    clientes = models.ManyToManyField(Cliente) 


class Rutaclientes(models.Model):
    fecha        = models.DateTimeField(auto_now_add=True, blank=True)
    modificacion = models.DateTimeField(auto_now=True, blank=True)
    ruta         = models.ForeignKey(Ruta, on_delete=models.CASCADE)
    cliente      = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    activo       = models.BooleanField(blank=True,default=True)
    estado       = models.BooleanField(blank=True,default=True)

    class Meta:
        managed = False
        db_table = 'app_ruta_clientes'

class Visita(models.Model):
    fecha        = models.DateTimeField(auto_now_add=True, blank=True)
    modificacion = models.DateTimeField(auto_now=True, blank=True)
    rutacliente  = models.ForeignKey(Rutaclientes, on_delete=models.CASCADE) 
    empleado     = models.ForeignKey('Empleado', on_delete=models.CASCADE)  # Field name made lowercase.
    nivel        = models.IntegerField(blank=True,null=True,default=1)
    activo       = models.BooleanField(blank=True,default=True)
    estado       = models.BooleanField(blank=True,default=True)
    clientes     = models.ManyToManyField(Cliente) 
    

class Error(models.Model):
    fecha        = models.DateTimeField(auto_now_add=True, blank=True)

app/templates/cliente/detalle.html
{% extends "base.html" %}
{% block imports %}
Información de Cliente

	<script >

  		var marker;  //variable de marcador

  		
  		var a= parseFloat('{{oCliente.latitud}}');
  		var b= parseFloat('{{oCliente.longitud}}');


  		$( document ).ready(function() {
    		console.log( "ready!" );
		});

	function initMap() {
	  	//const var1= -13.1680054;
	  	//const var2= -74.221639;
	    var uluru = {lat: a, lng: b};

	    var map = new google.maps.Map(document.getElementById('map'), {
	      zoom: 10,
	      center: uluru
	    });
	    var marker = new google.maps.Marker({
	      position: uluru,
	      map: map
	    });
	  }


	</script>
{% endblock %}

{% block title %}
Información de Cliente
{% endblock %}

{% block content %}
	<div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title">Datos de cliente</h3>
			<div>
				<table id="tCamiones"  class="table">	
					<tr>
						<td>Nombre: </td>
						<td>{{ oCliente.nombre }}</td>
					</tr>
					<tr>
						<td>Dirección: </td>
						<td>{{ oCliente.direccion }}</td>
					</tr>
					<tr>
						<td>N° Documento: </td>
						<td>{{ oCliente.numerodocumento }}</td>
					</tr>
					<tr>
						<td>Ubicación: </td>
						<td>{{ oCliente.longitud }} - {{ oCliente.latitud }}</td>
					</tr>
			</div>
			</div>

	    </div>
    </div>  
    		<label for="id_latitud">My Google Maps Demo</label><br>
			    			<div id="map" style="position: relative;overflow: hidden;height: 300px;">
							    <script async defer
							    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA94LBsliF6TX_7XT76lfJAopVP_h2RkkU&callback=initMap">
				    			</script>
				    			
			   			 	</div>
{% endblock %}

app/templates/cliente/editar.html
<!-- Usuario: Erick sulca
	 fecha: 01/06/18
	 última modificación: 12/06/18
	 Descripción: se agrego la función getMapa, y toggleBounce para hacer más dinámico el marcador del mapa -->

{% extends "base.html" %}

{% block imports %}

<!--
<script>

  		$( document ).ready(function() {
    		console.log( "ready!" );
		});
		function obtenerCoordenadas(){
        url = $('#id_url').val();
        var arrSlash = url.split("/");
        console.log(arrSlash);
        coordX=arrSlash[4].split(",")[0];
        coordX=coordX.substring(1, coordX.length);
        coordY=arrSlash[4].split(",")[1];
        $('#id_longitud').val(coordX);
		$('#id_latitud').val(coordY);
		initMap(parseFloat(coordX),parseFloat(coordY));

	}
	function initMap(coordX,coordY) {
	  	//const var1= -13.1680054;
	  	//const var2= -74.221639;
	    var uluru = {lat: parseFloat(coordX), lng: parseFloat(coordY)};

	    var map = new google.maps.Map(document.getElementById('map'), {
	      zoom: 20,
	      center: uluru
	    });
	    var marker = new google.maps.Marker({
	      position: uluru,
	      map: map
	    });
	  }

	</script>
-->
	<script >

	var marker;
	var coords={};

	initMap= function() {

		//usamos la API para geolocalización
		navigator.geolocation.getCurrentPosition(
				function (position){

					coords={
						lng: position.coords.longitude,
						lat: position.coords.latitude
					};

					setMapa(coords); //pasamos las coordenadas al método para crear el mapa.

				}, function(error){console.log(error);});
		}

		function setMapa(coords){

		var map=new google.maps.Map(document.getElementById('map'),
		{
			zoom: 13,
			center: new google.maps.LatLng(coords.lat, coords.lng),

		});

		marker = new google.maps.Marker({

			map: map,
			draggable: true,
			animation: google.maps.Animation.DROP,
			position: new google.maps.LatLng(coords.lat, coords.lng),


		});

		marker.addListener('click', toggleBounce);
		marker.addListener('dragend', function(event){

		   document.getElementById("id_latitud").value=this.getPosition().lat();
		   document.getElementById("id_longitud").value=this.getPosition().lng();
		});

	}


	function toggleBounce(){

		if(marker.getAnimation() !== null){
			marker.setAnimation(null);
		}else{
			marker.setAnimation(google.maps.Animation.BOUNCE);
		}
	}

	</script>
{% endblock %}

{% block title %}
Registrar Nuevo Cliente
{% endblock %}

{% block content %}
	<div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title">Formulario de nuevo cliente</h3>
                <form action="." method="post" enctype="multipart/form-data">
						{% csrf_token %}
				
				<ul>
   
				{% load widget_tweaks %}
				{% csrf_token %}
					<div class="form-group">
				    {% for field in form %}
							{{ field.errors }}
							{{ field.label_tag }}</br>
							{{ field|add_class:"form-control" }}
				    {% endfor %}



					<label for="id_latitud">My Google Maps Demo</label><br>
			    			<div id="map" style="position: relative;overflow: hidden;height: 300px;">
							    <script async defer
							    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA94LBsliF6TX_7XT76lfJAopVP_h2RkkU&callback=initMap">
				    			</script>
				    			
			   			 	</div>
			   		<br>
					<button class="btn btn-success" data-toggle="modal" data-target="">Actualizar</button>
				</ul>
				</form>
	    	</div>
	    </div>
    </div>
{% endblock %}

app/templates/cliente/listar.html
{% extends "base.html" %}
{% block imports %}

<script type="text/javascript">

//evento click para boton editar

$(document).on('Click', '.btn-editar', function(e){

	e.preventDefault();
	 var row=$(this).paren().parent()[0];
	 console.log(row);
});


</script>

{% endblock %}

{% block title %}
Clientes
{% endblock %}

{% block content %}
	<div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title">Lista de clientes</h3>
				{% load widget_tweaks %}
				{% csrf_token %}
					<div class="form-group">
					<table id="tCamiones"  class="table">	
						<thead>
	                        <tr>
	                            <th>#</th>
	                            <th>Nombre</th>
	                            <th>Dirección</th>
	                            <th>N° Documento</th>
	                            <th>Opciones</th>
	                        </tr>
	                    </thead>
				    {% for oCliente in oClientes %}
				    <tr>
				    	<td>{{ forloop.counter }}</td>
				    	<td>{{oCliente.nombre}}</td>
				    	<td>{{oCliente.direccion}}</td>
				    	<td>{{oCliente.numerodocumento}}</td>
				    	<td>
				    		<a href="/Cliente/detalle/{{oCliente.id}}/"><button type="button" class="btn btn-info">Ver</button> </a>
				    		<a href="/Cliente/editar/{{oCliente.id}}/"><button type="button" class="btn btn-primary btn-editar">Editar</button></a>
				    		<a href="/Cliente/eliminar/{{oCliente.id}}/"><button type="button" class="btn btn-danger btn-eliminar">Eliminar</button></a>
				    	</td>
				    </tr>

				    {% endfor %}

					</table>
				    <br>	
	    			<a href="/Cliente/nuevo/"><button type="button" class="btn btn-success">Nuevo Cliente</button> </a>
 
			</div>
	    </div>
    </div>  
{% endblock %}

app/templates/cliente/nuevo.html
<!-- Usuario: Erick sulca
	 fecha: 01/06/18
	 última modificación: 12/06/18
	 Descripción: se agrego la función getMapa, y toggleBounce para hacer más dinámico el marcador del mapa -->

{% extends "base.html" %}

{% block imports %}

<!--
<script>

  		$( document ).ready(function() {
    		console.log( "ready!" );
		});
		function obtenerCoordenadas(){
        url = $('#id_url').val();
        var arrSlash = url.split("/");
        console.log(arrSlash);
        coordX=arrSlash[4].split(",")[0];
        coordX=coordX.substring(1, coordX.length);
        coordY=arrSlash[4].split(",")[1];
        $('#id_longitud').val(coordX);
		$('#id_latitud').val(coordY);
		initMap(parseFloat(coordX),parseFloat(coordY));

	}
	function initMap(coordX,coordY) {
	  	//const var1= -13.1680054;
	  	//const var2= -74.221639;
	    var uluru = {lat: parseFloat(coordX), lng: parseFloat(coordY)};

	    var map = new google.maps.Map(document.getElementById('map'), {
	      zoom: 20,
	      center: uluru
	    });
	    var marker = new google.maps.Marker({
	      position: uluru,
	      map: map
	    });
	  }

	</script>
-->
	<script >

	var marker;
	var coords={};

	initMap= function() {

		//usamos la API para geolocalización
		navigator.geolocation.getCurrentPosition(
				function (position){

					coords={
						lng: position.coords.longitude,
						lat: position.coords.latitude
					};

					setMapa(coords); //pasamos las coordenadas al método para crear el mapa.

				}, function(error){console.log(error);});
		}

		function setMapa(coords){

		var map=new google.maps.Map(document.getElementById('map'),
		{
			zoom: 13,
			center: new google.maps.LatLng(coords.lat, coords.lng),

		});

		marker = new google.maps.Marker({

			map: map,
			draggable: true,
			animation: google.maps.Animation.DROP,
			position: new google.maps.LatLng(coords.lat, coords.lng),


		});

		marker.addListener('click', toggleBounce);
		marker.addListener('dragend', function(event){

		   document.getElementById("id_latitud").value=this.getPosition().lat();
		   document.getElementById("id_longitud").value=this.getPosition().lng();
		});

	}


	function toggleBounce(){

		if(marker.getAnimation() !== null){
			marker.setAnimation(null);
		}else{
			marker.setAnimation(google.maps.Animation.BOUNCE);
		}
	}

	</script>
{% endblock %}

{% block title %}
Registrar Nuevo Cliente
{% endblock %}

{% block content %}
	<div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title">Formulario de nuevo cliente</h3>
                <form action="." method="post" enctype="multipart/form-data">
					<ul>
						{% csrf_token %}
							<label for="id_nombre">Nombre:</label><br>
							<input type="text" name="nombre" id="id_nombre" required="" class="form-control" maxlength="45">

							<label for="id_direccion">Direccion:</label><br>
							<input type="text" name="direccion" id="id_direccion" required="" class="form-control" maxlength="45">
							<!--
							<label for="id_url" >URL Google Maps:</label><br>
                            <input type="text" name="longitud" id="id_url" class="form-control" onkeyup="obtenerCoordenadas()"><br>
							-->
							<label for="id_longitud">Longitud:</label><br>
							<input type="text" name="longitud" id="id_longitud" class="form-control" maxlength="50" readonly="readonly">

							<label for="id_latitud">Latitud:</label><br>
							<input type="text" name="latitud" id="id_latitud" class="form-control" maxlength="50" readonly="readonly">

							<label for="id_numerodocumento">Numerodocumento:</label><br>
							<input type="text" name="numerodocumento" id="id_numerodocumento" class="form-control" maxlength="11" >

					</ul>
				<ul>
   <!--
				{% load widget_tweaks %}
				{% csrf_token %}
					<div class="form-group">
				    {% for field in form %}
							{{ field.errors }}
							{{ field.label_tag }}</br>
							{{ field|add_class:"form-control" }}
				    {% endfor %}
-->
					<label for="id_latitud">My Google Maps Demo</label><br>
			    			<div id="map" style="position: relative;overflow: hidden;height: 300px;">
							    <script async defer
							    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA94LBsliF6TX_7XT76lfJAopVP_h2RkkU&callback=initMap">
				    			</script>
				    			
			   			 	</div>
			   		<br>
					<button class="btn btn-success" data-toggle="modal" data-target="">Agregar Cliente</button>
				</ul>
				</form>
	    	</div>
	    </div>
    </div>
{% endblock %}