ferreteria/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from app.views import *
from app.Views.productoView import *
from app.Views.precioView import *
from app.Views.presentacionView import *
from app.Views.aperturacajaView import *
from app.Views.cierrecajaView import *
from app.Views.operacionView import *
from app.Views.pedidoView import *
from app.Views.usuarioView import *
from app.Views.clienteView import *
from app.Views.rutaView import *
from app.Views.visitaView import *
from app.Views.errorView import *
from app.Views.ventaView import *
from app.Views.loteView import *
###########################################################
#   Usuario: Erick Sulca, Ulises Bejar
#   Fecha: 05/06/18
#   Última modificación:
#   Descripción: url registrarError
###########################################################

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home),
    url(r'^login/$', Login),
    url(r'^logout/$', Logout),
    url(r'^home/$', Home),
    url(r'^Home/$', Home),
    url(r'^prueba/$', Prueba),

    ################## Caja #######################
    url(r'^Caja/apertura/$', registrarAperturacaja),
    url(r'^Caja/cierre/$', registrarCierrecaja),
    url(r'^Caja/movimiento/$', registrarOperacion),

    ################## Venta #######################
    url(r'^Venta/nuevo/$', registrarPedido),

    ################## Producto #######################
    url(r'^Producto/listar/$', ListarProductos),
    url(r'^Producto/nuevo/$', registrarProducto),
    url(r'^Producto/detalle/(?P<producto_id>\d+)/$', detalleProducto),
    url(r'^Producto/editar/(?P<producto_id>\d+)/$', editarProducto),

    ################## Catalogo #######################
    url(r'^Presentacion/Listar/(?P<producto_id>\d+)/$', presentacion_detalle),
    url(r'^Presentacion/registrar/$', registrarPresentacionProducto),
    url(r'^Presentacion/eliminar/(?P<presentacion_id>\d+)/(?P<producto_id>\d+)/$', eliminarPresentacionProducto),
    url(r'^Presentacion/getPresentaciones/$', getPresentaciones),
    
    url(r'^Precios/getPrecios/$', getPrecios),
    #url(r'^pruebaExcel/$', IngresarPrecios),

    ################## Cliente #######################
    url(r'^Cliente/nuevo/$', nuevoCliente),
    url(r'^Cliente/detalle/(?P<cliente_id>\d+)/$', detalleCliente),
    url(r'^Cliente/editar/(?P<cliente_id>\d+)/$', editarCliente),
    url(r'^Cliente/listar/$', listarCliente),
    url(r'^Cliente/buscar/$', IngresarPrecios),
    url(r'^Cliente/actualizar/$', IngresarPrecios),
    
    ################## Pedidos #######################

    url(r'^Pedido/nuevo/$', registrarPedido),
    url(r'^Pedido/listar/$', ListarPedidos),
    url(r'^Pedido/resumen/$', ResumenPedidos),
    url(r'^Pedido/detalle/(?P<pedido_id>\d+)/$', DetallePedido),
    url(r'^Pedido/editar/(?P<pedido_id>\d+)/$', editarPedido),
    url(r'^Pedido/eliminar/(?P<pedido_id>\d+)/$', eliminarPedido),
    url(r'^Pedido/actualizar/$', IngresarPrecios),
    url(r'^Pedido/reporte/$', IngresarPrecios),
    url(r'^Pedido/buscar/$', IngresarPrecios),
    url(r'^Pedido/imprimir/$', IngresarPrecios),
    
    
    ################## APP Movil #######################
    
    url(r'^usuario/validar/$', validarUsuario),
    url(r'^usuario/ruta/$', rutaUsuario),

    url(r'^usuario/visita/cancelar/$', cancelarVisita),
    url(r'^usuario/visita/reiniciar/$', reiniciarVisita),

    url(r'^cliente/buscar/$', buscarCliente),
    url(r'^cliente/detalle/$', detalleClienteWS),

    url(r'^pedido/insertar/$', InstarPedido),
    url(r'^pedido/listar/$', ListarPedido),
    url(r'^pedido/detalle/$', DetallePedidoMovil),
    url(r'^pedido/editar/$', DetallePedidoMovil),

    url(r'^pago/nuevo/$', IngresarPrecios),


    url(r'^producto/buscar/$', BuscarProducto),
    url(r'^producto/presentacion/listar/$', ListarPresentacionesProducto),
    url(r'^producto/presentacion/cantidad/$', CantidadPresentacionesProducto),
    
    url(r'^error/registrar/$', registrarError),


#######################Ventas##############################

    url(r'^venta/nuevo/$', nuevoVenta),
    url(r'^venta/listar/$', ListarVentas),
    #url(r'^Producto/detalle/(?P<producto_id>\d+)/$', detalleProducto),
    #url(r'^Producto/editar/(?P<producto_id>\d+)/$', editarProducto),

    url(r'^Lote/nuevo/$', nuevoLote),
    #####################################################

#######################Rutas##############################

    #url(r'^Ruta/nuevo/$', nuevoVenta),
    #url(r'^Ruta/listar/$', ListarVenta),

#######################Información y Reportes##############################
    
    #url(r'^Reporte/almacen/$', reporteAlmacen),
    #url(r'^Reporte/caja/$', reporteCaja),
    #url(r'^Reporte/ventas/$', reporteVentas),

]

app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals
 
from django.db import models

###########################################################
#   Usuario: Erick Sulca, Ulises Bejar
#   Fecha: 04/06/18
#   Última modificación:
#   Descripción: crear modelo Error, etc
###########################################################

class Almacen(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

class Caja(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

class Aperturacaja(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=False)
    monto = models.FloatField()
    activo = models.BooleanField(blank=True,default=True)
    estado = models.BooleanField(blank=True,default=True)
    caja = models.ForeignKey(Caja, on_delete=models.CASCADE)

class Categoria(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

class Cierrecaja(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    monto = models.FloatField()
    estado = models.BooleanField(blank=True,default=True)
    aperturacaja = models.ForeignKey(Aperturacaja, on_delete=models.CASCADE)  # Field name made lowercase.

class Cliente(models.Model):
    nombre = models.CharField(max_length=45)
    direccion = models.CharField(max_length=45)
    longitud = models.CharField(max_length=25, blank=True, null=True)
    latitud = models.CharField(max_length=25, blank=True, null=True)
    numerodocumento = models.CharField(max_length=11, blank=True, null=True)
    estado = models.BooleanField(blank=True,default=True)

class Cobro(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    monto = models.FloatField()
    estado = models.BooleanField(blank=True,default=True)
    venta = models.ForeignKey('Venta', on_delete=models.CASCADE)  # Field name made lowercase.
    recibo = models.ForeignKey('Recibo', blank=True, null=True, on_delete=models.CASCADE)  # Field name made lowercase.

class Detalletipooperacion(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)
    tipooperacion = models.ForeignKey('Tipooperacion', on_delete=models.CASCADE)  # Field name made lowercase.

class Lote(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    modificado = models.DateTimeField(auto_now=True, blank=True)
    estado = models.BooleanField(blank=True,default=True)
    proveedor = models.ForeignKey('Proveedor', on_delete=models.CASCADE)  # Field name made lowercase.
    recibo = models.ForeignKey('Recibo', on_delete=models.CASCADE)  # Field name made lowercase.

class Operacion(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    monto = models.FloatField()
    descripcion = models.TextField(blank=True, null=True)
    estado = models.BooleanField(blank=True,default=True)
    caja = models.ForeignKey(Caja, on_delete=models.CASCADE)  # Field name made lowercase.
    detalletipooperacion = models.ForeignKey(Detalletipooperacion, on_delete=models.CASCADE)  # Field name made lowercase.
    cobro = models.ForeignKey(Cobro, blank=True, null=True, on_delete=models.CASCADE)  # Field name made lowercase.

class Pedido(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    estado = models.BooleanField(blank=True,default=True)
    empleado = models.ForeignKey('Empleado', on_delete=models.CASCADE)  # Field name made lowercase.
    cliente = models.ForeignKey(Cliente, blank=True, null=True, on_delete=models.CASCADE)  # Field name made lowercase.

class Precio(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

class Presentacion(models.Model):
    nombre = models.CharField(max_length=45)
    codigo = models.CharField(max_length=45, blank=True, null=True)
    estado = models.BooleanField(blank=True,default=True)

class Empleado(models.Model):
    nombre = models.CharField(max_length=45)
    imei = models.CharField(max_length=45, blank=True, null=True)
    imagen = models.ImageField(blank=True, null=True)#upload_to='%Y/%m/%d',
    perfil = models.IntegerField(blank=True, null=True,default=1)
    estado = models.BooleanField(blank=True,default=True)

class Producto(models.Model):
    nombre = models.CharField(max_length=45)
    codigo = models.CharField(max_length=45, blank=True, null=True)
    cantidad = models.FloatField(default=0,blank=True, null=True)
    imagen = models.ImageField(upload_to='', blank=True, null=True)#upload_to='%Y/%m/%d',
    url = models.CharField(max_length=100, blank=True, null=True)
    valor = models.FloatField(default=1,blank=True)
    estado = models.BooleanField(blank=True,default=True)
    presentacions = models.ManyToManyField(Presentacion)

class Productopresentacions(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE) 
    presentacion = models.ForeignKey(Presentacion, on_delete=models.CASCADE)  
    valor = models.FloatField()
    unidadprincipal = models.BooleanField(default=False,blank=True)
    precios = models.ManyToManyField(Precio)
    class Meta:
        managed = False
        db_table = 'app_producto_presentacions'

class Producto_almacens(models.Model):
    cantidad = models.FloatField()
    cantidadinicial = models.FloatField()
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)  # Field name made lowercase.
    almacen = models.ForeignKey(Almacen, on_delete=models.CASCADE)  # Field name made lowercase.
    lote = models.ForeignKey(Lote, on_delete=models.CASCADE)  # Field name made lowercase.

class Producto_categorias(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)  # Field name made lowercase.
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)  # Field name made lowercase.

class Proveedor(models.Model):
    nombre = models.CharField(max_length=45)
    direccion = models.CharField(max_length=45)
    documento = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

class Recibo(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

class Tipooperacion(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

class Venta(models.Model):
    fecha   = models.DateTimeField(auto_now_add=True, blank=True)
    monto   = models.FloatField()
    nrecibo = models.CharField(max_length=45, blank=True, null=True)
    estado  = models.BooleanField(blank=True,default=True)
    pedido  = models.ForeignKey(Pedido, on_delete=models.CASCADE)  # Field name made lowercase.
    cliente = models.ForeignKey(Cliente, blank=True, null=True, on_delete=models.CASCADE)  # Field name made lowercase.
 
class Pedidoproductospresentacions(models.Model):
    valor                 = models.FloatField(blank=True, null=True)
    cantidad              = models.FloatField(blank=True,default=0)
    pedido                = models.ForeignKey(Pedido, on_delete=models.CASCADE)  # Field name made lowercase.
    productopresentacions = models.ForeignKey('Productopresentacions', on_delete=models.CASCADE)  # Field name made lowercase.
    class Meta:
        managed = False
        db_table = 'app_pedido_productos_presentacions'

class Productopresentacionsprecios(models.Model):
    precio                = models.ForeignKey(Precio, on_delete=models.CASCADE)  # Field name made lowercase.
    productopresentacions = models.ForeignKey('Productopresentacions', on_delete=models.CASCADE)  # Field name made lowercase.
    valor                 = models.FloatField(blank=True,default=0)
    class Meta:
        managed = False
        db_table = 'app_producto_presentacions_precios'


class Ruta(models.Model):
    nombre   = models.CharField(max_length=45)
    fecha    = models.DateTimeField(auto_now_add=True, blank=True)
    activo   = models.BooleanField(blank=True,default=True)
    estado   = models.BooleanField(blank=True,default=True)
    clientes = models.ManyToManyField(Cliente) 


class Rutaclientes(models.Model):
    fecha        = models.DateTimeField(auto_now_add=True, blank=True)
    modificacion = models.DateTimeField(auto_now=True, blank=True)
    ruta         = models.ForeignKey(Ruta, on_delete=models.CASCADE)
    cliente      = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    activo       = models.BooleanField(blank=True,default=True)
    estado       = models.BooleanField(blank=True,default=True)

    class Meta:
        managed = False
        db_table = 'app_ruta_clientes'

class Visita(models.Model):
    fecha        = models.DateTimeField(auto_now_add=True, blank=True)
    modificacion = models.DateTimeField(auto_now=True, blank=True)
    rutacliente  = models.ForeignKey(Rutaclientes, on_delete=models.CASCADE) 
    empleado     = models.ForeignKey('Empleado', on_delete=models.CASCADE)  # Field name made lowercase.
    nivel        = models.IntegerField(blank=True,null=True,default=1)
    activo       = models.BooleanField(blank=True,default=True)
    estado       = models.BooleanField(blank=True,default=True)
    clientes     = models.ManyToManyField(Cliente) 
    

class Error(models.Model):
    fecha        = models.DateTimeField(auto_now_add=True, blank=True)

app/templates/pedido/detalle.html
{% extends "base.html" %}
{% block imports %}
Información de Cliente
{% endblock %}

{% block title %}
Información de Cliente
{% endblock %}

{% block content %}
	<div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title">Detalle de pedido</h3>
			<div>
				<table id="tCamiones"  class="table">	
					<tr>
						<td>Nombre: </td>
						<td>{{ oCliente.nombre }}</td>
					</tr>
					<tr>
						<td>Dirección: </td>
						<td>{{ oCliente.direccion }}</td>
					</tr>
					<tr>
						<td>N° Documento: </td>
						<td>{{ oCliente.numerodocumento }}</td>
					</tr>
					
				</table>	
				<br>	
				<table id="tProductos"  class="table">			
					<thead>
	                    <tr>
	                        <th>#</th>
	                        <th>Producto</th>
	                        <th>Presentación</th>
	                        <th>Cantidad</th>
	                	</tr>
	                </thead>
	                {% for oProducto in oProductos %}
				    <tr>
				    	<td>{{ forloop.counter }}</td>
				    	<td>{{oProducto.nombreProducto}}</td>
				    	<td>{{oProducto.nombrePresentacion}}</td>
				    	<td>{{oProducto.cantidad}}</td>
				    </tr>

				    {% endfor %}
				</table>	

			</div>
			</div>

	    </div>
    </div>  
{% endblock %}

app/templates/pedido/editar.html
 
{% extends "base.html" %}

{% block imports %}
{% endblock %}

{% block title %}
Registrar Nuevo Cliente
{% endblock %}

{% block content %}
	<div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title">Editar Pedido</h3>
                <form action="." method="post" enctype="multipart/form-data">
						{% csrf_token %}
				
				<ul>
  
				{% load widget_tweaks %}
				{% csrf_token %}
					<div class="form-group">
				    {% for field in form %}
							{{ field.errors }}
							{{ field.label_tag }}</br>
							{{ field|add_class:"form-control" }}
				    {% endfor %}
		   		<br>
					<button class="btn btn-success" data-toggle="modal" data-target="">Actualizar</button>
				</ul>
				</form>
	    	</div>
	    </div>
    </div>
{% endblock %}

app/templates/pedido/eliminar.html
{% extends "base.html" %}

{% block imports %}
{% endblock %}


{% block content %}
	<div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title">Desea eliminar el pedido de {{oPedido.cliente.nombre}}</h3>
                <form action="." method="post" enctype="multipart/form-data">
						{% csrf_token %}
				
				<ul>
					<button class="btn btn-danger" type="sumit">Si, eliminar</button>
					<a href="{% url 'Pedido/listar' %}">Cancelar</a>
				</ul>
				</form>
	    	</div>
	    </div>
    </div>
{% endblock %}

app/templates/pedido/listar.html
{% extends "base.html" %}
{% block imports %}
Clientes
{% endblock %}

{% block title %}
Clientes
{% endblock %}

{% block content %}
	<div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title">Lista de pedidos</h3>
				{% load widget_tweaks %}
				{% csrf_token %}
					<div class="form-group">
					<table id="tCamiones"  class="table">	
						<thead>
	                        <tr>
	                            <th>#</th>
	                            <th>Fecha</th>
	                            <th>Cliente</th>
	                            <th>Dirección</th>
	                            <th>Opciones</th>
	                        </tr>
	                    </thead>
				    {% for oPedido in oPedidos %}
				    <tr>
				    	<td>{{ forloop.counter }}</td>
				    	<td>{{oPedido.fecha}}</td>
				    	<td>{{oPedido.cliente.nombre}}</td>
				    	<td>{{oPedido.cliente.direccion}}</td>
				    	<td>{{oPedido.empleado.nombre}}</td>
				    	<td>{{oPedido.producto.nombre}}</td>
				    	<td>

				    	 /*  se cambio el nombre **\
				    		<a href="/Pedido/detalle/{{oPedido.id}}/"><button type="button" class="btn btn-info">Ver</button> </a>
				    		<a href="/Pedido/editar/{{oPedido.id}}/"><button type="button" class="btn btn-primary">Editar</button></a>
				    		<a href="/Pedido/eliminar/{{oPedido.id}}/"><button type="button" class="btn btn-danger">Eliminar</button></a>
				    	</td>
				    </tr>

				    {% endfor %}

					</table>
				    <br>	
	    			<a href="/Pedido/nuevo/"><button type="button" class="btn btn-success">Nuevo Pedido</button> </a>
				    <br>	
				    <br>	
	    			<a href="/Pedido/resumen/"><button type="button" class="btn btn-primary btn-lg">Resumen de Pedidos</button> </a>
 
			</div>
	    </div>
    </div>  
{% endblock %}

app/templates/pedido/nuevo.html
{% extends "base.html" %}
{% block imports %}
<script type="text/javascript" src="/static/js/crearPedido.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $( "#inpt-producto" ).focus();
        $('cantidad').prop('disabled', true);
        $( "#inpt-producto" ).autocomplete({
            source: function (request, response) {

                var datos = {nombreProducto: $("#inpt-producto").val()};
                var sendData = JSON.stringify(datos); 
                $.ajax({
                    type: "POST",
                    dataType: "json",
                    url: "/producto/buscar/",
                    data: sendData,
                    contentType: "application/json; charset=utf-8",
                    async: false,
                    cache: false,
                    CrossDomain: true,

                    success: function (result) {
                    var ListasProductos = result['productos'];
                    response($.map(ListasProductos, function (item) {
                        return {
                            label: item.nombre,
                            idproducto: item.nombre,
                            precio: item.precio,
                            codigo: item.codigo,
                            Id: item.id
                            };
                        }));
                    }
                });
            },
            minLength: 2,
            select: function (event, ui) {
                $.data(document.body, 'idproducto', ui.item.Id);//guardar el id en memoria el $.data guarda en memoria
                $( "#precio" ).val( ui.item.precio);
                $( "#codigo" ).val( ui.item.codigo);

                $( "#cantidad" ).focus();
                $( "#cantidad" ).focus();
                var iDPro = ui.item.Id;
                //agregar();
            }


        });
  });

</script>

 <style>
    ul.ui-autocomplete {
        z-index: 1100;
    }
    #content{
        position: absolute;
        min-height: 50%;
        width: 80%;
        top: 20%;
        left: 5%;
    }

    .selected{
        cursor: pointer;
    }
    .selected:hover{
        background-color: #0585C0;
        color: white;
    }
    .seleccionada{
        background-color: #0585C0;
        color: white;
    }
</style>
{% endblock %}


{% block title %}
Nueva Venta
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title">Nuevo Pedido</h3>

                <label for="id_cliente">Cliente:</label>
                <br>
                <input type="text" name="cliente" id="cliente" required="" class="form-control" maxlength="45">
                <br>
                <label for="id_nombre">Producto:</label>
                <br>
                <input type="text" name="inpt-producto" id="inpt-producto" required="" class="form-control" maxlength="45">
                <br>
                <label for="id_nombre">Código:</label>
                <br>
                <input type="text" name="codigo" id="codigo" required="" class="form-control" disabled="disabled">
                <br>
                <!-- <label for="id_nombre">Precio:</label> 
                <br>
                <input type="number" name="precio" id="precio" required="" class="form-control">
                <br>-->
                <label for="id_nombre">Cantidad:</label>
                <br>
                <input type="number" name="cantidad" id="cantidad" required="" class="form-control" >
                <br>
                <button id="bt_add" class="btn btn-success">Agregar</button>
                <button id="bt_del" class="btn btn-warning">Eliminar</button>
                <button id="bt_delall" class="btn btn-danger">Eliminar todo</button>
            
                    <div class="row">
                        <div class="form-group">
                            <label ><center>Concepto Operación</center></label>
                            <table id="tabla" class="table table-bordered">
                            <thead>
                                <tr>
                                    <td>Nº</td>
                                    <td>Cantidad</td>
                                    <td>Cod. Producto</td>
                                    <td>Nombre</td>
                                    <td>Precio Unit.</td>
                                    <td>Total</td>
                                </tr>
                            </thead>
                            </table>

                            <br>
                        </div>
                            TOTAL: S/. <label for="id_Total" id="id_Total" name="id_Total"></label>
                            <br>
                            <br>

                        <button id="bt_GenerarVenta" class="btn btn-success">Generar Venta</button>

                    </div>

                    <div class="row">
                        <div class="form-group">
                            <div class="col-sm-8 col-md-8 col-lg-6">
                                <div id="tabs" style="display:none;">
                                    <table id="listaProducto"></table>
                                    <div id="pagerlistaProducto"  style="text-align: center;"></div>
                                </div>
                            </div>

                            <div class="col-sm-2 col-md-2 col-lg-4">

                            </div>
                        </div>
                    </div>
                       
                    
    </div>  
{% endblock %}

app/templates/pedido/resumen.html
{% extends "base.html" %}
{% block imports %}
Información de Cliente
{% endblock %}

{% block title %}
Información de Cliente
{% endblock %}

{% block content %}
	<div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title">Resumen de pedido</h3>
			<div>
				
				<table id="tProductos"  class="table">			
					<thead>
	                    <tr>
	                        <th>#</th>
	                        <th>Producto</th>
	                        <th>Presentación</th>
	                        <th>Cantidad</th> 
	                	</tr>
	                </thead>
	                {% for oProducto in oProductos %}
				    <tr>
				    	<td>{{ forloop.counter }}</td>
				    	<td>{{oProducto.nombreProducto}}</td>
				    	<td>{{oProducto.nombrePresentacion}}</td>
				    	<td>{{oProducto.cantidad}}</td>
				    </tr>

				    {% endfor %}
				</table>	

			</div>
			</div>

	    </div>
    </div>  
{% endblock %}